import { describe, expect, it } from "vitest";
import { buildDimensionConfigurations, buildDimensionDefinitions, buildDimensionSelectionIndex, normalizeDimensionValueSelections, resolveDimensionSelection } from "./dimension-selector";
import type { BenchmarkConfigurationIds, LoadedBenchmarkDatabase } from "./types";

const configuration = (code_state_id: string, hardware_environment_id: string, software_environment_id: string): BenchmarkConfigurationIds => ({ code_state_id, hardware_environment_id, software_environment_id });
function fixtureDatabase(): LoadedBenchmarkDatabase {
  return { benchmarksByKey: new Map(), runsById: new Map(), codeStatesById: new Map([["c1", { id: "c1", label: "C1", code_date: "2026-01-01", identity: { source: { kind: "git", revision: "a" } }, metadata: {} }], ["c2", { id: "c2", label: "C2", code_date: "2026-01-02", identity: { source: { kind: "git", revision: "b" } }, metadata: {} }]]), hardwareEnvironmentsById: new Map([["h1", { id: "h1", label: "CPU A", identity: { architecture: "x86_64", cpu: { vendor: "AMD", model: "CPU A" }, gpu: [{ vendor: "NVIDIA", model: "A" }, { vendor: "AMD", model: "B" }] }, metadata: {} }], ["h2", { id: "h2", label: "CPU B", identity: { architecture: "x86_64", cpu: { vendor: "Intel", model: "CPU B" }, gpu: [{ vendor: "NVIDIA", model: "B" }, { vendor: "AMD", model: "A" }] }, metadata: {} }]]), softwareEnvironmentsById: new Map([["s1", { id: "s1", label: "Julia 1.10.11", identity: { runtime: { name: "Julia", version: "1.10.11" } }, metadata: {} }], ["s2", { id: "s2", label: "Julia 1.10.12", identity: { runtime: { name: "Julia", version: "1.10.12" } }, metadata: {} }]]), configurations: [configuration("c1", "h1", "s1"), configuration("c2", "h1", "s1"), configuration("c1", "h1", "s2"), configuration("c2", "h1", "s2"), configuration("c1", "h2", "s1")], viewCatalog: { metricOptions: [], metricSourcesByLabel: new Map(), branchOptions: ["all"], databaseTimeStart: "", databaseTimeEnd: "" }, stats: { rowCount: 0, runCount: 0, keyCount: 0, hardwareEnvironmentCount: 2, softwareEnvironmentCount: 2, configurationCount: 5, metrics: [], latestRunDate: "", dirtyRunCount: 0 }, metadata: { schema_version: 6, name: "", description: "", project_url: "", logo_url: "", logo_url_dark: "", created_at: "", updated_at: "", notes: "", raw: {} }, source_label: "fixture", source_url: null };
}

function chainFixtureDatabase(): LoadedBenchmarkDatabase {
  const base = fixtureDatabase();
  const codeStatesById = new Map([["c1", { id: "c1", label: "Git A", code_date: "2026-01-01", identity: { source: { kind: "git", revision: "a", diff_digest: "d1" } }, metadata: {} }], ["c2", { id: "c2", label: "Git B", code_date: "2026-01-02", identity: { source: { kind: "git", revision: "b", diff_digest: "d2" } }, metadata: {} }], ["c3", { id: "c3", label: "Archive", code_date: "2026-01-03", identity: { source: { kind: "archive", revision: "pkg-1", diff_digest: "p1" } }, metadata: {} }]]);
  const softwareEnvironmentsById = new Map([["s1", { id: "s1", label: "Julia 1.10", identity: { platform: { os: { name: "Ubuntu", version: "24.04" }, kernel: { name: "Linux", version: "6.8" } }, runtime: { name: "Julia", version: "1.10" }, gpu: { interface: { name: "CUDA", version: "12.4" } }, gpu_runtime: { backend: "cuda", runtime: { name: "CUDA", version: "12.4" } }, benchmark: { framework: { name: "BenchmarkTools", version: "1.6" } }, dependencies: { kind: "lock", format: "json", digest: "sd1" } }, metadata: {} }], ["s2", { id: "s2", label: "Julia 1.11", identity: { platform: { os: { name: "Ubuntu", version: "22.04" }, kernel: { name: "Linux", version: "5.15" } }, runtime: { name: "Julia", version: "1.11" }, gpu: { interface: { name: "CUDA", version: "12.5" } }, gpu_runtime: { backend: "cuda", runtime: { name: "CUDA", version: "12.5" } }, benchmark: { framework: { name: "BenchmarkTools", version: "1.7" } }, dependencies: { kind: "lock", format: "toml", digest: "sd2" } }, metadata: {} }], ["s3", { id: "s3", label: "C 23", identity: { platform: { os: { name: "Fedora", version: "40" }, kernel: { name: "Linux", version: "6.9" } }, runtime: { name: "C", version: "23" }, gpu: { interface: { name: "OpenCL", version: "3.0" } }, gpu_runtime: { backend: "opencl", runtime: { name: "OpenCL", version: "3.0" } }, benchmark: { framework: { name: "GoogleBenchmark", version: "1.8" } }, dependencies: { kind: "manifest", format: "json", digest: "sd3" } }, metadata: {} }]]);
  const configurations = ["c1", "c2", "c3"].flatMap((code) => ["s1", "s2", "s3"].map((software) => configuration(code, "h1", software))).concat([configuration("c1", "h2", "s2"), configuration("c2", "h2", "s2"), configuration("c1", "h2", "s3")]);
  return { ...base, codeStatesById, softwareEnvironmentsById, configurations, stats: { ...base.stats, configurationCount: configurations.length, softwareEnvironmentCount: softwareEnvironmentsById.size } };
}

describe("Dimension Selector domain logic", () => {
  it("discovers scalar dimensions while keeping object-array collections atomic", () => {
    const configurations = buildDimensionConfigurations(fixtureDatabase()); const dimensions = buildDimensionDefinitions(configurations);
    expect(dimensions.map((dimension) => dimension.label)).toEqual(expect.arrayContaining(["Code / Source / Revision", "Hardware / CPU / Model", "Hardware / GPU", "Software / Runtime / Version"]));
    expect(dimensions.some((dimension) => dimension.label.includes("GPU / Vendor"))).toBe(false);
  });

  it("keeps exactly one dimension free and turns every other dimension into a condition", () => {
    const configurations = buildDimensionConfigurations(fixtureDatabase()); const dimensions = buildDimensionDefinitions(configurations); const revision = dimensions.find((dimension) => dimension.label === "Code / Source / Revision")!;
    const selection = resolveDimensionSelection({ index: buildDimensionSelectionIndex(configurations, dimensions), varyingDimensionKeys: [revision.key], valueSelections: [] });
    expect(selection.varyingDimension?.key).toBe(revision.key);
    expect(selection.fixedValueSelections.some((selector) => selector.dimension.key === revision.key)).toBe(false);
    expect(selection.configurationKeys.length).toBeGreaterThan(1);
  });

  it("treats one selected fixed value as exact and multiple selected values as one grouped condition", () => {
    const configurations = buildDimensionConfigurations(fixtureDatabase()); const dimensions = buildDimensionDefinitions(configurations); const revision = dimensions.find((dimension) => dimension.label === "Code / Source / Revision")!; const version = dimensions.find((dimension) => dimension.label === "Software / Runtime / Version")!; const base = resolveDimensionSelection({ index: buildDimensionSelectionIndex(configurations, dimensions), varyingDimensionKeys: [revision.key], valueSelections: [] }); const values = base.fixedValueSelections.find((entry) => entry.dimension.key === version.key)!.options;
    const exact = resolveDimensionSelection({ index: buildDimensionSelectionIndex(configurations, dimensions), varyingDimensionKeys: [revision.key], valueSelections: [{ dimensionKey: version.key, valueKeys: [values[0].key] }] });
    expect(exact.fixedValueSelections.find((entry) => entry.dimension.key === version.key)?.valueKeys).toEqual([values[0].key]);
    const grouped = resolveDimensionSelection({ index: buildDimensionSelectionIndex(configurations, dimensions), varyingDimensionKeys: [revision.key], valueSelections: [{ dimensionKey: version.key, valueKeys: values.map((value) => value.key) }] });
    expect(grouped.fixedValueSelections.find((entry) => entry.dimension.key === version.key)?.valueKeys).toEqual(values.map((value) => value.key));
    expect(grouped.configurationKeys).toEqual(expect.arrayContaining(['["c1","h1","s1"]', '["c1","h1","s2"]']));
  });
  it("allows temporary zero or multiple varying dimensions and reports them as invalid", () => {
    const configurations = buildDimensionConfigurations(fixtureDatabase()); const dimensions = buildDimensionDefinitions(configurations); const revision = dimensions.find((dimension) => dimension.label === "Code / Source / Revision")!; const cpu = dimensions.find((dimension) => dimension.label === "Hardware / CPU / Model")!;
    const zero = resolveDimensionSelection({ index: buildDimensionSelectionIndex(configurations, dimensions), varyingDimensionKeys: [], valueSelections: [] }); expect(zero.validation.isValid).toBe(false); expect(zero.configurationKeys).toEqual([]);
    const multiple = resolveDimensionSelection({ index: buildDimensionSelectionIndex(configurations, dimensions), varyingDimensionKeys: [revision.key, cpu.key], valueSelections: [] }); expect(multiple.validation.isValid).toBe(false); expect(multiple.configurationKeys).toEqual([]);
  });

  it("preserves an empty multi-value selection while keeping single-value dimensions fixed", () => {
    const configurations = buildDimensionConfigurations(fixtureDatabase()); const dimensions = buildDimensionDefinitions(configurations); const revision = dimensions.find((dimension) => dimension.label === "Code / Source / Revision")!; const version = dimensions.find((dimension) => dimension.label === "Software / Runtime / Version")!; const kind = dimensions.find((dimension) => dimension.label === "Code / Source / Kind")!;
    const selection = resolveDimensionSelection({ index: buildDimensionSelectionIndex(configurations, dimensions), varyingDimensionKeys: [revision.key], valueSelections: [{ dimensionKey: version.key, valueKeys: [] }, { dimensionKey: kind.key, valueKeys: [] }] });
    expect(selection.fixedValueSelections.find((entry) => entry.dimension.key === version.key)?.valueKeys).toEqual([]); expect(selection.fixedValueSelections.find((entry) => entry.dimension.key === kind.key)?.valueKeys).toHaveLength(1); expect(selection.validation.isValid).toBe(false); expect(selection.validation.issues).toContain("Software / Runtime / Version must select at least 1 value."); expect(selection.validation.issues).not.toContain("Code / Source / Kind must select at least 1 value."); expect(selection.configurationKeys).toEqual([]);
  });

  it("filters Hardware dimensions from top to bottom without reverse filtering", () => {
    const configurations = buildDimensionConfigurations(fixtureDatabase()); const dimensions = buildDimensionDefinitions(configurations); const index = buildDimensionSelectionIndex(configurations, dimensions); const revision = dimensions.find((dimension) => dimension.label === "Code / Source / Revision")!; const vendor = dimensions.find((dimension) => dimension.label === "Hardware / CPU / Vendor")!; const model = dimensions.find((dimension) => dimension.label === "Hardware / CPU / Model")!; const vendorOptions = index.optionsByDimensionKey.get(vendor.key)!; const modelOptions = index.optionsByDimensionKey.get(model.key)!; const amd = vendorOptions.find((value) => value.label === "AMD")!.key, intel = vendorOptions.find((value) => value.label === "Intel")!.key, cpuB = modelOptions.find((value) => value.label === "CPU B")!.key;
    const fromVendor = resolveDimensionSelection({ index, varyingDimensionKeys: [revision.key], valueSelections: [{ dimensionKey: vendor.key, valueKeys: [amd] }] }); expect(fromVendor.fixedValueSelections.find((entry) => entry.dimension.key === model.key)?.options.map((option) => option.label)).toEqual(["CPU A"]);
    const fromModel = resolveDimensionSelection({ index, varyingDimensionKeys: [revision.key], valueSelections: [{ dimensionKey: vendor.key, valueKeys: [intel] }, { dimensionKey: model.key, valueKeys: [cpuB] }] }); expect(fromModel.fixedValueSelections.find((entry) => entry.dimension.key === vendor.key)?.options.map((option) => option.label)).toEqual(["AMD", "Intel"]);
  });

  it("ignores an empty Hardware selection when filtering later values while keeping validation invalid", () => {
    const configurations = buildDimensionConfigurations(fixtureDatabase()); const dimensions = buildDimensionDefinitions(configurations); const index = buildDimensionSelectionIndex(configurations, dimensions); const revision = dimensions.find((dimension) => dimension.label === "Code / Source / Revision")!; const vendor = dimensions.find((dimension) => dimension.label === "Hardware / CPU / Vendor")!; const model = dimensions.find((dimension) => dimension.label === "Hardware / CPU / Model")!;
    const selection = resolveDimensionSelection({ index, varyingDimensionKeys: [revision.key], valueSelections: [{ dimensionKey: vendor.key, valueKeys: [] }] });
    expect(selection.fixedValueSelections.find((entry) => entry.dimension.key === model.key)?.options.map((option) => option.label)).toEqual(["CPU A", "CPU B"]); expect(selection.validation.isValid).toBe(false); expect(selection.validation.issues).toContain("Hardware / CPU / Vendor must select at least 1 value.");
  });

  it("filters non-Hardware values by Hardware context while remembering temporarily unavailable choices", () => {
    const configurations = buildDimensionConfigurations(fixtureDatabase()); const dimensions = buildDimensionDefinitions(configurations); const index = buildDimensionSelectionIndex(configurations, dimensions); const revision = dimensions.find((dimension) => dimension.label === "Code / Source / Revision")!; const vendor = dimensions.find((dimension) => dimension.label === "Hardware / CPU / Vendor")!; const model = dimensions.find((dimension) => dimension.label === "Hardware / CPU / Model")!; const version = dimensions.find((dimension) => dimension.label === "Software / Runtime / Version")!; const vendorOptions = index.optionsByDimensionKey.get(vendor.key)!; const modelOptions = index.optionsByDimensionKey.get(model.key)!; const versionOptions = index.optionsByDimensionKey.get(version.key)!; const amd = vendorOptions.find((value) => value.label === "AMD")!.key, intel = vendorOptions.find((value) => value.label === "Intel")!.key, cpuA = modelOptions.find((value) => value.label === "CPU A")!.key, cpuB = modelOptions.find((value) => value.label === "CPU B")!.key, version112 = versionOptions.find((value) => value.label === "1.10.12")!.key;
    const onCpuB = resolveDimensionSelection({ index, varyingDimensionKeys: [revision.key], valueSelections: [{ dimensionKey: vendor.key, valueKeys: [intel] }, { dimensionKey: model.key, valueKeys: [cpuB] }, { dimensionKey: version.key, valueKeys: [version112] }] }); const filteredVersion = onCpuB.fixedValueSelections.find((entry) => entry.dimension.key === version.key)!; expect(filteredVersion.options.map((option) => option.label)).toEqual(["1.10.11"]); expect(filteredVersion.valueKeys).toEqual([filteredVersion.options[0].key]); expect(filteredVersion.rememberedValueKeys).toEqual([version112]);
    const onCpuA = resolveDimensionSelection({ index, varyingDimensionKeys: [revision.key], valueSelections: [{ dimensionKey: vendor.key, valueKeys: [amd] }, { dimensionKey: model.key, valueKeys: [cpuA] }, { dimensionKey: version.key, valueKeys: [version112] }] }); expect(onCpuA.fixedValueSelections.find((entry) => entry.dimension.key === version.key)?.options.map((option) => option.label)).toEqual(["1.10.11", "1.10.12"]); expect(onCpuA.fixedValueSelections.find((entry) => entry.dimension.key === version.key)?.valueKeys).toEqual([version112]);
  });

  it("builds an acyclic filtering graph only from Hardware precedence and explicit identity hierarchies", () => {
    const configurations = buildDimensionConfigurations(chainFixtureDatabase()); const dimensions = buildDimensionDefinitions(configurations); const index = buildDimensionSelectionIndex(configurations, dimensions); const labels = new Map(dimensions.map((dimension, dimensionIndex) => [dimension.label, dimensionIndex]));
    const upstreamLabels = (label: string) => index.filterUpstreamIndicesByDimensionIndex[labels.get(label)!].map((dimensionIndex) => dimensions[dimensionIndex].label);
    expect(upstreamLabels("Code / Source / Revision")).toContain("Code / Source / Kind"); expect(upstreamLabels("Code / Source / Diff digest")).toEqual(expect.arrayContaining(["Code / Source / Kind", "Code / Source / Revision"]));
    expect(upstreamLabels("Software / Platform / OS / Version")).toContain("Software / Platform / OS / Name"); expect(upstreamLabels("Software / Platform / Kernel / Version")).toContain("Software / Platform / Kernel / Name"); expect(upstreamLabels("Software / Runtime / Version")).toContain("Software / Runtime / Name");
    expect(upstreamLabels("Software / GPU / Interface / Version")).toContain("Software / GPU / Interface / Name"); expect(upstreamLabels("Software / GPU runtime / Runtime / Name")).toContain("Software / GPU runtime / Backend"); expect(upstreamLabels("Software / GPU runtime / Runtime / Version")).toEqual(expect.arrayContaining(["Software / GPU runtime / Backend", "Software / GPU runtime / Runtime / Name"]));
    expect(upstreamLabels("Software / Benchmark / Framework / Version")).toContain("Software / Benchmark / Framework / Name"); expect(upstreamLabels("Software / Dependencies / Digest")).toEqual(expect.arrayContaining(["Software / Dependencies / Kind", "Software / Dependencies / Format"]));
    expect(upstreamLabels("Software / Runtime / Version")).not.toContain("Software / Platform / OS / Name"); expect(index.filterResolutionOrder).toHaveLength(dimensions.length);
  });

  it("applies explicit one-way parent-child filtering without unrelated Software cross-filtering", () => {
    const configurations = buildDimensionConfigurations(chainFixtureDatabase()); const dimensions = buildDimensionDefinitions(configurations); const index = buildDimensionSelectionIndex(configurations, dimensions); const revision = dimensions.find((dimension) => dimension.label === "Code / Source / Revision")!; const runtimeName = dimensions.find((dimension) => dimension.label === "Software / Runtime / Name")!; const runtimeVersion = dimensions.find((dimension) => dimension.label === "Software / Runtime / Version")!; const osName = dimensions.find((dimension) => dimension.label === "Software / Platform / OS / Name")!; const runtimeNames = index.optionsByDimensionKey.get(runtimeName.key)!, runtimeVersions = index.optionsByDimensionKey.get(runtimeVersion.key)!, osNames = index.optionsByDimensionKey.get(osName.key)!; const julia = runtimeNames.find((option) => option.label === "Julia")!.key, c = runtimeNames.find((option) => option.label === "C")!.key, version23 = runtimeVersions.find((option) => option.label === "23")!.key, fedora = osNames.find((option) => option.label === "Fedora")!.key;
    const fromName = resolveDimensionSelection({ index, varyingDimensionKeys: [revision.key], valueSelections: [{ dimensionKey: runtimeName.key, valueKeys: [julia] }] }); expect(fromName.fixedValueSelections.find((entry) => entry.dimension.key === runtimeVersion.key)?.options.map((option) => option.label)).toEqual(["1.10", "1.11"]);
    const fromVersion = resolveDimensionSelection({ index, varyingDimensionKeys: [revision.key], valueSelections: [{ dimensionKey: runtimeName.key, valueKeys: [c, julia] }, { dimensionKey: runtimeVersion.key, valueKeys: [version23] }] }); expect(fromVersion.fixedValueSelections.find((entry) => entry.dimension.key === runtimeName.key)?.options.map((option) => option.label)).toEqual(["C", "Julia"]);
    const fromOs = resolveDimensionSelection({ index, varyingDimensionKeys: [revision.key], valueSelections: [{ dimensionKey: osName.key, valueKeys: [fedora] }] }); expect(fromOs.fixedValueSelections.find((entry) => entry.dimension.key === runtimeName.key)?.options.map((option) => option.label)).toEqual(["C", "Julia"]);
  });

  it("combines Hardware context with local filtering chains and ignores empty upstream selections", () => {
    const configurations = buildDimensionConfigurations(chainFixtureDatabase()); const dimensions = buildDimensionDefinitions(configurations); const index = buildDimensionSelectionIndex(configurations, dimensions); const revision = dimensions.find((dimension) => dimension.label === "Code / Source / Revision")!; const vendor = dimensions.find((dimension) => dimension.label === "Hardware / CPU / Vendor")!; const model = dimensions.find((dimension) => dimension.label === "Hardware / CPU / Model")!; const runtimeName = dimensions.find((dimension) => dimension.label === "Software / Runtime / Name")!; const runtimeVersion = dimensions.find((dimension) => dimension.label === "Software / Runtime / Version")!; const vendorOptions = index.optionsByDimensionKey.get(vendor.key)!, modelOptions = index.optionsByDimensionKey.get(model.key)!, runtimeNames = index.optionsByDimensionKey.get(runtimeName.key)!; const intel = vendorOptions.find((option) => option.label === "Intel")!.key, cpuB = modelOptions.find((option) => option.label === "CPU B")!.key, julia = runtimeNames.find((option) => option.label === "Julia")!.key;
    const filtered = resolveDimensionSelection({ index, varyingDimensionKeys: [revision.key], valueSelections: [{ dimensionKey: vendor.key, valueKeys: [intel] }, { dimensionKey: model.key, valueKeys: [cpuB] }, { dimensionKey: runtimeName.key, valueKeys: [julia] }] }); expect(filtered.fixedValueSelections.find((entry) => entry.dimension.key === runtimeVersion.key)?.options.map((option) => option.label)).toEqual(["1.11"]);
    const emptyName = resolveDimensionSelection({ index, varyingDimensionKeys: [revision.key], valueSelections: [{ dimensionKey: runtimeName.key, valueKeys: [] }] }); expect(emptyName.fixedValueSelections.find((entry) => entry.dimension.key === runtimeVersion.key)?.options.map((option) => option.label)).toEqual(["1.10", "1.11", "23"]); expect(emptyName.validation.issues).toContain("Software / Runtime / Name must select at least 1 value.");
  });

  it("filters Code source fields in one direction and remembers local selections that become unavailable", () => {
    const configurations = buildDimensionConfigurations(chainFixtureDatabase()); const dimensions = buildDimensionDefinitions(configurations); const index = buildDimensionSelectionIndex(configurations, dimensions); const varying = dimensions.find((dimension) => dimension.label === "Hardware / CPU / Model")!; const kind = dimensions.find((dimension) => dimension.label === "Code / Source / Kind")!; const revision = dimensions.find((dimension) => dimension.label === "Code / Source / Revision")!; const runtimeName = dimensions.find((dimension) => dimension.label === "Software / Runtime / Name")!; const runtimeVersion = dimensions.find((dimension) => dimension.label === "Software / Runtime / Version")!; const kinds = index.optionsByDimensionKey.get(kind.key)!, revisions = index.optionsByDimensionKey.get(revision.key)!, runtimeNames = index.optionsByDimensionKey.get(runtimeName.key)!, runtimeVersions = index.optionsByDimensionKey.get(runtimeVersion.key)!; const git = kinds.find((option) => option.label === "git")!.key, archive = kinds.find((option) => option.label === "archive")!.key, pkg = revisions.find((option) => option.label === "pkg-1")!.key, julia = runtimeNames.find((option) => option.label === "Julia")!.key, c = runtimeNames.find((option) => option.label === "C")!.key, version111 = runtimeVersions.find((option) => option.label === "1.11")!.key;
    const fromKind = resolveDimensionSelection({ index, varyingDimensionKeys: [varying.key], valueSelections: [{ dimensionKey: kind.key, valueKeys: [git] }] }); expect(fromKind.fixedValueSelections.find((entry) => entry.dimension.key === revision.key)?.options.map((option) => option.label)).toEqual(["a", "b"]);
    const fromRevision = resolveDimensionSelection({ index, varyingDimensionKeys: [varying.key], valueSelections: [{ dimensionKey: kind.key, valueKeys: [archive, git] }, { dimensionKey: revision.key, valueKeys: [pkg] }] }); expect(fromRevision.fixedValueSelections.find((entry) => entry.dimension.key === kind.key)?.options.map((option) => option.label)).toEqual(["archive", "git"]);
    const onC = resolveDimensionSelection({ index, varyingDimensionKeys: [varying.key], valueSelections: [{ dimensionKey: runtimeName.key, valueKeys: [c] }, { dimensionKey: runtimeVersion.key, valueKeys: [version111] }] }); const cVersion = onC.fixedValueSelections.find((entry) => entry.dimension.key === runtimeVersion.key)!; expect(cVersion.options.map((option) => option.label)).toEqual(["23"]); expect(cVersion.rememberedValueKeys).toEqual([version111]);
    const onJulia = resolveDimensionSelection({ index, varyingDimensionKeys: [varying.key], valueSelections: [{ dimensionKey: runtimeName.key, valueKeys: [julia] }, { dimensionKey: runtimeVersion.key, valueKeys: [version111] }] }); expect(onJulia.fixedValueSelections.find((entry) => entry.dimension.key === runtimeVersion.key)?.valueKeys).toEqual([version111]);
  });

  it("normalizes persisted fixed-value selections", () => {
    expect(normalizeDimensionValueSelections([{ dimensionKey: "d1", valueKeys: ["a", "a", "b", 3] }, { dimensionKey: "d1", valueKeys: [] }, { dimensionKey: "", valueKeys: ["x"] }, null])).toEqual([{ dimensionKey: "d1", valueKeys: [] }]);
  });

});
