# SPDX-FileCopyrightText: 2026 karei
# SPDX-License-Identifier: MIT-0

name: Benchmarks Scheduled

on:
  schedule:
    - cron: "0 3 * * 1"

permissions:
  contents: write

jobs:
  benchmark:
    uses: ./.github/workflows/Benchmarks.yml
